# Generated by Django 5.1.5 on 2025-05-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
